#
# 				Makefile
#                              Mark NOBLE
#                       Ecole des Mines de Paris
#
# created first 04.09.97 M.N.    (Solaris 2.5, Linux RedHat)
######################################################################
# Instructions:
#	Make changes where necessary to reflect the needs of your
#	system, by commenting and uncommenting necessary lines
######################################################################
#                     C Compiler
# SUN SOLARIS: cc.4.0
#CC=cc
# GNU compiler 2.7.1
CC=gcc
# Ibm sp2 C compiler
#CC=xlc
# Sun C language convention (not ansi) : needed for Time_2d
#CLANG= -Xs
##gcc not ansi C: needed for Time_2d, underscore (pb interface F77 et C)
#CLANG= -traditional -fno-underscoring
#CLANG= -ansi
#CLANG= -traditional
##IBM sp2
#CLANG=-langvl=classic
######################################################################
#                     Fortran Compiler
# sun f77.4.0 
#FC=f77
# gnu compiler (not tested yet)
FC=gfortran
# IBM sp2
#FC=xlf
######################################################################
#                     Optimisation Flags
# Sun f77 -e is 132 Chars ,ext_.. for C and f77 interface, -O4 max opt
#FFLAGS= -e -ext_names=plain -xO4
# GNU g77
FFLAGS= -O3 -fno-underscoring
# IBM sp2
#FFLAGS=-O3 -qfixed=132 -qarch=pwr2 -qstrict -qtune -qipa
# Sun C 
#CFLAGS= -xO4
# gcc
CFLAGS= -O3
# IBM sp2
#CFLAGS= -O3
######################################################################
#                      IEEE
# Sun f77 for nonstandard floating point
#FFLOAT=-fns
# Sun C if use fortran nonstandard floatinp pt., use also for C
#CFLOAT=-fns
# Sun f77, enable overflow, division by zero traps
#TRAP = -ftrap=overflow,division
#gcc non infinity defined for Time_2d
CINF=-DNO_IEEE_PROTOCOL 
# IBM sp2 for Time_2d
#CINF=-DNO_IEEE_INFINITY
######################################################################
#                      LD Libraries
# Sun 
#LDFLAGS    = -lm -lsunmath
# Linux
LDFLAGS    = -lm
#
######################################################################
#
#                  SUFFIXES
SUFFIXES = .o .c .f
.SUFFIXES: $(SUFFIXES)
# Fortran section
COMPILE.f=$(FC) $(FFLAGS) $(FFLOAT) $(TRAP) -c
.f.o:
	$(COMPILE.f) $<
# C section
COMPILE.c=$(CC) $(CFLAGS) $(CFLOAT) $(TRAP) $(CINF) $(CLANG) -c
.c.o:
	$(COMPILE.c) $<
